# Generated by Django 4.1.1 on 2022-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('event_admin', models.IntegerField()),
                ('approved_user', models.JSONField()),
                ('pending_users', models.JSONField()),
                ('start_date', models.DateField()),
                ('price', models.IntegerField()),
                ('hhhh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.IntegerField()),
                ('stopping', models.JSONField()),
                ('destination', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('route_type', models.CharField(choices=[('Car', 'Car'), ('Bicycle', 'Bicycle')], default='Car', max_length=50)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
