# Generated by Django 4.1.1 on 2022-10-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_review_remove_event_hhhh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pending_users',
        ),
        migrations.AddField(
            model_name='event',
            name='event_users',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stopping',
            field=models.CharField(max_length=50),
        ),
    ]
